### ISSUE TITLE
Updating many-to-many relationship values in model.

### ISSUE THREAD

**Issue by shortcodes** [mindz-team/laravel-relationships#3]
Problem:
When updating many-to-many relation via this package there is a situation where there is a nessecity to pass specific structure of data. For example:

`POST` /books

```
{
    "name": "Example name",
    "published_at": "2022-08-08",
    "tags": [
          {
              "id":1
          },
          {
              "id":2
          }
     ]
}
```

Above example works but if we add a little twist (for example when front application want to pass returned parameters in request) like this

```
{
    "name": "Example name",
    "published_at": "2022-08-08",
    "tags": [
          {
              "id":1,
              "name": "Horror"
          },
          {
              "id":2,
              "name": "Sensation"
          }
     ]
}
```

There is an exeption raised by mysql that field `name` is not in pivot table. 

Resolution:

Check if using Pivot models that extends`Illuminate\Database\Eloquent\Relations\Pivot` class can be working as filters for attributes that are not in pivot tables. Especially by `guard` attribute.

**Comment by mg10110** [comment]
Solution:
- add pivot model and attach it to relation,
- add `fillable` attribute to pivot model and add all fields you want to edit in pivot table
- now only the fields you set in `fillable` attribute will be saved, even if you pass extra params (without throwing an exception)

todo:
- prepare some generic solution to make it easier...

**Comment by tomasztryka** [comment]
Solution proposed by @mg10110 was discussed and approved.
